Example adapted from [this online post](https://nextjournal.com/gkoehler/digit-recognition-with-keras).

In [1]:
from keras.datasets import mnist
from keras.utils import np_utils

(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


reshape the data

In [2]:
num_training = X_train.shape[0]
num_test = X_test.shape[0]
width = X_train.shape[1]
height = X_train.shape[2]
num_pixels = width * height
X_flat_train = X_train.reshape(X_train.shape[0], num_pixels).astype('float32')
X_flat_test = X_test.reshape(X_test.shape[0], num_pixels).astype('float32')
X_flat_train /= 255
X_flat_test /= 255
width
height
num_pixels

784

In [3]:
X_flat_train.shape

(60000, 784)

In [4]:
X_flat_test.shape

(10000, 784)

Prepare target values using 1-hot encoding

In [5]:
y_encoded_train = np_utils.to_categorical(y_train)
y_encoded_test = np_utils.to_categorical(y_test)

In [6]:
y_encoded_train.shape

(60000, 10)

build a one layer dense network

In [7]:
from keras.models import Sequential, load_model
from keras.layers.core import Dense, Activation

model_0 = Sequential()

model_0.add(Dense(512, input_shape=(784,)))
model_0.add(Activation('sigmoid'))                            

model_0.add(Dense(10))
model_0.add(Activation('softmax'))

In [8]:
model_0.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [9]:
model_0.fit(X_flat_train, y_encoded_train,
          batch_size=128, epochs=10,
          verbose=2,
          validation_data=(X_flat_test, y_encoded_test))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 3s - loss: 0.4501 - acc: 0.8808 - val_loss: 0.2696 - val_acc: 0.9197
Epoch 2/10
 - 3s - loss: 0.2468 - acc: 0.9291 - val_loss: 0.2223 - val_acc: 0.9327
Epoch 3/10
 - 3s - loss: 0.1935 - acc: 0.9441 - val_loss: 0.1733 - val_acc: 0.9487
Epoch 4/10
 - 3s - loss: 0.1545 - acc: 0.9549 - val_loss: 0.1412 - val_acc: 0.9575
Epoch 5/10
 - 3s - loss: 0.1264 - acc: 0.9636 - val_loss: 0.1254 - val_acc: 0.9639
Epoch 6/10
 - 2s - loss: 0.1051 - acc: 0.9702 - val_loss: 0.1140 - val_acc: 0.9659
Epoch 7/10
 - 3s - loss: 0.0874 - acc: 0.9752 - val_loss: 0.1011 - val_acc: 0.9694
Epoch 8/10
 - 3s - loss: 0.0737 - acc: 0.9792 - val_loss: 0.0867 - val_acc: 0.9729
Epoch 9/10
 - 3s - loss: 0.0631 - acc: 0.9821 - val_loss: 0.0847 - val_acc: 0.9741
Epoch 10/10
 - 3s - loss: 0.0537 - acc: 0.9850 - val_loss: 0.0784 - val_acc: 0.9765


building a linear stack of densely connected layers with the sequential model from keras

![](nn_example.png)

In [10]:
model = Sequential()

model.add(Dense(512, input_shape=(784,)))
model.add(Activation('relu'))                            

model.add(Dense(512))
model.add(Activation('relu'))

model.add(Dense(10))
model.add(Activation('softmax'))

In [11]:
# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [12]:
model.fit(X_flat_train, y_encoded_train,
          batch_size=128, epochs=10,
          verbose=2,
          validation_data=(X_flat_test, y_encoded_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 4s - loss: 0.2206 - acc: 0.9358 - val_loss: 0.1048 - val_acc: 0.9658
Epoch 2/10
 - 4s - loss: 0.0797 - acc: 0.9750 - val_loss: 0.0804 - val_acc: 0.9740
Epoch 3/10
 - 4s - loss: 0.0512 - acc: 0.9840 - val_loss: 0.0698 - val_acc: 0.9785
Epoch 4/10
 - 3s - loss: 0.0366 - acc: 0.9884 - val_loss: 0.0664 - val_acc: 0.9805
Epoch 5/10
 - 3s - loss: 0.0267 - acc: 0.9912 - val_loss: 0.0646 - val_acc: 0.9818
Epoch 6/10
 - 4s - loss: 0.0219 - acc: 0.9927 - val_loss: 0.0736 - val_acc: 0.9796
Epoch 7/10
 - 4s - loss: 0.0197 - acc: 0.9936 - val_loss: 0.0772 - val_acc: 0.9798
Epoch 8/10
 - 4s - loss: 0.0163 - acc: 0.9943 - val_loss: 0.0717 - val_acc: 0.9812
Epoch 9/10
 - 3s - loss: 0.0138 - acc: 0.9956 - val_loss: 0.0852 - val_acc: 0.9787
Epoch 10/10
 - 3s - loss: 0.0162 - acc: 0.9946 - val_loss: 0.0830 - val_acc: 0.9803


Compute model accuracy on the 10,000 testing examples 

In [13]:
loss_and_metrics = model.evaluate(X_flat_test, y_encoded_test, verbose=2)

print("Test Loss", loss_and_metrics[0])
print("Test Accuracy", loss_and_metrics[1])

Test Loss 0.08297560409503567
Test Accuracy 0.9803


To save a trained model: we save its structure and its weights.

In [14]:
# open('mnist_simple_ann_model_structure.json', 'w').write(model.to_json())
# model.save_weights('mnist_simple_ann_model_weights.h5')
# model.save('mnist_simple_ann.h5')

Load saved model

In [15]:
# from keras.models import model_from_json
# model = model_from_json(open('mnist_simple_ann_model_structure.json').read())
# model.load_weights('mnist_simple_ann_model_weights.h5')
#new_model = load_model('mnist_simple_ann.h5')

In [50]:
import cv2
import numpy as np
img = cv2.imread('C:/Users/julia/Desktop/Fall 2019/ML/lab/week12/numberafterprocessing.png', 0)
# img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
height, width = img.shape
img = img.flatten().astype('float32')
img /= 255
proba = model.predict(np.array( [img,] ))
y_classes = model.predict_classes(np.array( [img,] ))
output = proba.argmax()
print(model.predict_classes(np.array( [img,] )))
print(proba[0])
print(output)
print(y_classes)

[4]
[2.1435208e-12 3.8246117e-10 7.7497592e-11 1.7567309e-11 9.9994171e-01
 7.8273075e-14 3.0241406e-12 5.8286372e-05 9.1878727e-12 2.0600362e-08]
4
[4]


In [36]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [39]:
a = X_train[0].reshape(1, num_pixels).astype('float32')
a /= 255
a

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [48]:
img

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02352941,
       0.07843138, 0.07843138, 0.02352941, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     